### ISSUE TITLE
One More Small Change for Vortex version 

### ISSUE THREAD

**Issue by ChemGuy1611** [AlanParadis/Stalker2SimpleModMerger#2]
Almost everything on v1.4.1 for the Vortex version is working great now. 

The only issue is with the mod paks being moved to the temp folder and then moved back to the ~mods folder. When moved back, the paks end up in the ~mods folder directly, rather than in the individual folders they were sorted into by Vortex for load ordering. 

I think the easiest way to fix this is to simply COPY the paks to the temp folder for merging rather than MOVING them. Then, the temp files can be deleted after merger. This should be more reliable and will avoid this issue altogether.

Thank you so much for your excellent work on this tool!

**Comment by AlanParadis** [comment]
I remove the copy to a temporary directory as this was not needed, so this is fixed in https://github.com/AlanParadis/Stalker2SimpleModMerger/releases/tag/Vortex-v1.4.2

**Comment by ChemGuy1611** [comment]
@AlanParadis Thanks for the quick response! I did notice that the linked release does not have the files there.

**Comment by AlanParadis** [comment]
I uploaded it
