### ISSUE TITLE
Additional Bugs in Vortex Version v1.4.2

### ISSUE THREAD

**Issue by ChemGuy1611** [AlanParadis/Stalker2SimpleModMerger#5]
Results of testing v1.4.2 for Vortex:

1. the relocating of the pak files mentioned in Issue #2 is still present.
2. Additionally, I am getting errors for incorrect command when extracting pakchunk0-Windows.pak as seen previously in Issue #1 (item 1). 

3. I am also getting errors related to some mods including Engine.ini and .txt files inside the pak. I had not seen this error in prior versions.

```
Total .pak files found: 20

File path for Engine/Config/Windows/WindowsEngine.ini not found in ZZFrancisLouisSOVRAM_P.pak.
Do you want to try to fetch the file path from the base pak? (yes/no): yes
ERROR: Could not find a part of the path 'C:\Program Files (x86)\Steam\steamapps\common\S.T.A.L.K.E.R. 2 Heart of Chornobyl\Stalker2SimpleModMerger\Engine\Config\Windows'.
Base file for  not found in .

File path for MADE_BY_FRANCISLOUIS.txt not found in ZZFrancisLouisSOVRAM_P.pak.
Do you want to try to fetch the file path from the base pak? (yes/no):
```

4. Also getting a File Save Error when auto-merging with KDiff3. First time getting this as well. I am using the same two mods I used in testing for prior versions that modify CoreVariables.cfg.

EDIT: I think this is related to the merged mods not being updated for the latest game version. It seems there needs to be some way to check for this because if this happens the script will get stuck in a loop that can only be ended by closing the script window, leaving behind folders of the extracted paks.

![snap0024](https://github.com/user-attachments/assets/5b6ddf3c-de9e-4086-965f-a541cd4a67cc)

**Comment by AlanParadis** [comment]
This patch should address most of the issues but I was unable to reproduce the bug with pakchunk0-Windows.pak. It extract just fine on my pc

**Comment by ChemGuy1611** [comment]
Seems to be working fine now. Thank you!
