### ISSUE TITLE
pakchunk0 file name for Xbox Game Pass version

### ISSUE THREAD

**Issue by ChemGuy1611** [AlanParadis/Stalker2SimpleModMerger#6]
The pakchunk0 file for the xbox version has filename "pakchunk0-WinGDK.pak". The script will need to adjust this name based on which version of the game executable is present (either "Stalker2.exe" or "gamelaunchelper.exe").

This applies to both the mainline and Vortex versions.

**Comment by AlanParadis** [comment]
Fixed in https://github.com/AlanParadis/Stalker2SimpleModMerger/releases/tag/Vortex-v1.4.4
